### ISSUE TITLE
reading data from excel

### ISSUE THREAD

**Issue by ajasja** [kalekundert/wellmap#34]
Sometimes it's just easier to make a plate layout in excel.

Would reading plate layouts from excel be out of scope for wellmap?

I know plateo and bioplate have a subset of that functionality (that might or might not be working :) 

But reading excel layout with wellmap would be great. So I'm wondering if you would accept pull request with this functionality.

**Comment by kalekundert** [comment]
I think this is probably out of scope, but I do see the appeal in having more ways to specify layouts.

In my view, one big issue with this idea is that there are a number of "regular" wellmap features that would be hard to reproduce in excel, e.g. namely the `extras` argument to `load()` and all the `meta` settings.  If excel files were limited to analysis scripts that didn't use any of these features, I think that would be a pretty substantial drawback, and a source of confusion.

Perhaps it would be best to implement something like this in a third-party library.

**Comment by ajasja** [comment]
Sounds good! 

I'll be implementing this anyway. For most of the non-computational people I ask, an excel layout is much easier to make & understand. 

Currently this is the layout I'm planning to read (and it does have both the [expt] as well as the [meta] sections :).
![image](https://user-images.githubusercontent.com/19926/196516139-9bfec08b-1af2-4496-a4fa-35638644a09a.png)

For example, this will read the `sample` names and `pHs` as well as set `c_protein_nM` etc...

Any feedback is welcome!

Best, 
Ajasja

**Comment by kalekundert** [comment]
That looks pretty good.  I do have some comments, which you can take or leave:

- I wonder if it would be better to not special-case the "experiment" values, and instead just have the user create a table for each variable, even if every well has the same value.  It would force users to do a bit more typing/dragging, and it wouldn't be quite as easy to read, but it would also reduce the number of rules that users need to remember.

- I'd recommend copying the [`plater`](https://cran.r-project.org/web/packages/plater/vignettes/plater-basics.html) format.  You're pretty close already, but there's at least one small discrepancy (the position of the variable names w.r.t. the row/column labels), and maybe more if you look carefully.  IMO, `plater` is the best microplate-parsing library out there (other than wellmap, of course :smile:), so I think it makes sense to use it as a model.  And all else being equal, it's nice for different tools to take compatible inputs.

- Regarding merging something like this into wellmap, my concern really is that the entire `load()` API would need to be supported, otherwise different scripts might require different *kinds* of wellmap files, and that just seems like a bad situation.  The incompatibilities I can foresee are:

  1. The values loaded by `load(extras=True)` are often dicts/lists, and excel doesn't have a way to represent structured data.  Maybe you could do something like the `metadata` column you already have, where the cells are interpreted as JSON or something, but frankly that feels too messy/hacky.  I can't think of any alternatives, though.
  
  2. The `meta.path` and `meta.paths` options are important for linking the layout and the data.  The `paths` option can be a dict or a list, which brings up the same problems as above.

  3. I'd be inclined to move the metadata/extras values into their own worksheets, rather than having them alongside the wells.  This just seems more "clean" to me, and it also allows for more strict compatibility with the `plater` format.

- If you upload this to PyPI, let me know.  I'd happily include a link to it in the docs.
